---
- hosts: test
  become: true
  tasks:
  - name: Create user user1
    user:
      name: user1
      password: '$6$kjPn3KClxO.Lujw$BjDr2y4vvJK3Q.C/nLET.A/FD9OxN6DNASmLetapq9LiXVVlTrYnvlEGuITZiVkV3JhX.vbsZ68/hnbdRsYnx1'
      shell: /bin/bash
      append: yes
  - name: Создать SSH ключ для user1 в ~user1/.ssh/id_rsa
    user:
      name: user1
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  - name: Добавить authorized key из файла id_rsa.pub
    authorized_key:
      user: user1
      state: present
      key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
